---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui
  namespace: streamlink
  labels:
    app: kafbat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafbat-ui
  template:
    metadata:
      labels:
        app: kafbat-ui
    spec:
      containers:
      - name: kafbat-ui
        image: ghcr.io/kafbat/kafka-ui:latest
        env:
        - name: DYNAMIC_CONFIG_ENABLED
          value: "true"
        - name: KAFKA_CLUSTERS_0_NAME
          value: "streamlink-kafka"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka.streamlink.svc.cluster.local:9092"
        - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
          value: "http://schemaregistry.streamlink.svc.cluster.local:8081"
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
          value: "streamlink-connect"
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
          value: "http://kafka-connect.streamlink.svc.cluster.local:8083"
        - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
          value: "http://ksqldb-server.streamlink.svc.cluster.local:8088"
        # OAuth2 Authentication with Keycloak
        - name: AUTH_TYPE
          value: "OAUTH2"
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_CLIENTID
          valueFrom:
            configMapKeyRef:
              name: streamlink-config
              key: keycloak-kafbat-ui-client-id
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: kafbat-client-secret
              optional: true
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_SCOPE
          value: "openid"
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_REDIRECT-URI
          valueFrom:
            configMapKeyRef:
              name: streamlink-config
              key: keycloak-kafbat-ui-redirect-uri
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_ISSUER-URI
          valueFrom:
            configMapKeyRef:
              name: streamlink-config
              key: keycloak-issuer-uri
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_USER-NAME-ATTRIBUTE
          value: "preferred_username"
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_CLIENT-NAME
          value: "Keycloak"
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_PROVIDER
          value: "keycloak"
        - name: AUTH_OAUTH2_CLIENT_KEYCLOAK_CUSTOM-PARAMS_TYPE
          value: "oauth"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/"
        - name: LOGGING_LEVEL_ROOT
          value: "INFO"
        - name: LOGGING_LEVEL_COM_PROVECTUS
          value: "INFO"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafbat-ui
  namespace: streamlink
  labels:
    app: kafbat-ui
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: kafbat-ui
