---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: streamlink
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        command:
        - sh
        - -c
        - |
          # Create config file
          cat > /tmp/kraft.properties <<EOF
          node.id=1
          process.roles=broker,controller
          controller.quorum.voters=1@localhost:9093
          listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          advertised.listeners=PLAINTEXT://kafka:9092
          controller.listener.names=CONTROLLER
          listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          log.dirs=/var/lib/kafka/data
          offsets.topic.replication.factor=1
          transaction.state.log.replication.factor=1
          transaction.state.log.min.isr=1
          auto.create.topics.enable=true
          EOF
          
          # Format storage if not already formatted
          if [ ! -f /var/lib/kafka/data/meta.properties ]; then
            echo "Formatting Kafka storage..."
            /opt/kafka/bin/kafka-storage.sh format -t MkU3OEVBNTcwNTJENDM2Qk -c /tmp/kraft.properties
          fi
          
          # Start Kafka
          echo "Starting Kafka..."
          exec /opt/kafka/bin/kafka-server-start.sh /tmp/kraft.properties
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9093
          name: controller
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: streamlink
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: plaintext
  selector:
    app: kafka
